name: refresh database

on:
  schedule:
    - cron: "0 20 * * *"    #runs at 1:00pm-2pm depending on daylight savings ET everyday

jobs:
  getdataandrefreshmap:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9 #install the python needed
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: execute py script
        run: |
          python pool_scraper.py
          git config user.name "github-actions"
          git config user.email "action@users.noreply.github.com"

          # Pull the latest changes from the remote repository
          git pull https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ThierryJones21/lane_swim_webapp.git main --rebase
          
          git add .
          git commit -m "crongenerated database refresh"
         
          # Add, commit, and push changes
          git diff-index --quiet HEAD || (git add . && git commit -m "cron-generated database refresh" && git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ThierryJones21/lane_swim_webapp.git HEAD:main)
